### ISSUE TITLE
Add test to CI

### ISSUE THREAD

**Issue by spiccinini** [solfernandez/achordarte#7]
filename `.github/workflows/tests.yaml`
```
name: Tests

on: [push]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Run tests
        run: pytest -v
```
